from flask import Flask, request, send_file, jsonify
import os
import whisper
from moviepy.editor import VideoFileClip
from datetime import datetime
import threading
import time

app = Flask(__name__)
UPLOAD_FOLDER = 'uploads'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

# Cleanup function for old files
def cleanup_old_files():
    while True:
        try:
            now = time.time()
            for filename in os.listdir(UPLOAD_FOLDER):
                file_path = os.path.join(UPLOAD_FOLDER, filename)
                if os.path.isfile(file_path) and (now - os.stat(file_path).st_mtime) > 48 * 3600:
                    os.remove(file_path)
        except:
            pass
        time.sleep(6 * 3600)  # Check every 6 hours

# Start cleanup thread
cleanup_thread = threading.Thread(target=cleanup_old_files, daemon=True)
cleanup_thread.start()

@app.route('/')
def serve_frontend():
    return send_file('index.html')

@app.route('/upload', methods=['POST'])
def upload_file():
    if 'video' not in request.files:
        return jsonify({'error': 'No file uploaded'}), 400
    
    file = request.files['video']
    language = request.form.get('language', 'english')
    
    if file.filename == '':
        return jsonify({'error': 'No file selected'}), 400
    
    # Save uploaded file
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{timestamp}_{file.filename}"
    filepath = os.path.join(UPLOAD_FOLDER, filename)
    file.save(filepath)
    
    try:
        # Extract audio
        video = VideoFileClip(filepath)
        audio_filename = f"{timestamp}_audio.mp3"
        audio_path = os.path.join(UPLOAD_FOLDER, audio_filename)
        video.audio.write_audiofile(audio_path)
        
        # Generate transcript
        model = whisper.load_model("base")
        result = model.transcribe(filepath, language=language if language != 'hindi' else 'hi')
        
        transcript_filename = f"{timestamp}_transcript.txt"
        transcript_path = os.path.join(UPLOAD_FOLDER, transcript_filename)
        
        with open(transcript_path, 'w', encoding='utf-8') as f:
            f.write(f"Transcript generated by Red Universe AI\n")
            f.write(f"Video: {file.filename}\n")
            f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Language: {language}\n\n")
            f.write(result['text'])
        
        return jsonify({
            'success': True,
            'audio_file': audio_filename,
            'transcript_file': transcript_filename
        })
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/download/<filename>')
def download_file(filename):
    try:
        return send_file(
            os.path.join(UPLOAD_FOLDER, filename),
            as_attachment=True,
            download_name=filename
        )
    except FileNotFoundError:
        return jsonify({'error': 'File not found'}), 404

if __name__ == '__main__':
    app.run(debug=True)
